print("_  __                     ")
print("| |/ /__  ____  ____  ____")
print("/   /  __/ / / / /_/ / / //")
print("/_/|____/_/ /_/____/_/ /_/")
print("============================")
sleep(0.3)
print("Welcome to Xenon Operating System ")
sleep(0.5)
print("Installing the System...")
sleep(0.8)
shell.run("wget https://raw.githubusercontent.com/nexus331/xenon/refs/heads/main/himars.lua?token=GHSAT0AAAAAACZ7QOOOXO5XRZE3WGRIFKD6ZZPMDDQ")
shell.run("wget run https://basalt.madefor.cc/install.lua release latest.lua")
