print("_  __                     ")
print("| |/ /__  ____  ____  ____")
print("/   /  __/ / / / /_/ / / //")
print("/_/|____/_/ /_/____/_/ /_/")
print("============================")
sleep(0.3)
print("Welcome to Xenon Operating System ")
print("Press [ENTER] To install Xenon")
sleep(0.5)
print("Installing the System...")
sleep(0.8)
shell.run("wget https://raw.githubusercontent.com/nexus331/xenon/refs/heads/main/srs.lua?token=GHSAT0AAAAAACZ7QOOPAGSM6IIJWUSYLSBUZZQ2UDA")
shell.run("wget https://raw.githubusercontent.com/nexus331/xenon/refs/heads/main/himars.lua?token=GHSAT0AAAAAACZ7QOOOCI25GFQP4ZPFI3MQZZQ2TYA")
shell.run("wget run https://basalt.madefor.cc/install.lua release latest.lua")
