print("_  __                     ")
print("| |/ /__  ____  ____  ____")
print("/   /  __/ / / / /_/ / / //")
print("/_/|____/_/ /_/____/_/ /_/")
print("============================")
sleep(0.3)
print("Welcome to Xenon Operating System ")
print("Press [ENTER] To install Xenon")
sleep(0.5)
print("Installing the System...")
sleep(0.8)
print("Installing Bootstrap")
shell.run("wget https://raw.githubusercontent.com/nexus331/xenon/refs/heads/main/bootstrap.lua")
print("Installing Rednet Server")
shell.run("wget https://raw.githubusercontent.com/nexus331/xenon/refs/heads/main/rednet-himars.lua")
print(" Installing Xenon CoreOS")
shell.run("wget https://raw.githubusercontent.com/nexus331/xenon/refs/heads/main/xenon.lua")
print("Installing Rednet Client")
shell.run("wget https://raw.githubusercontent.com/nexus331/xenon/refs/heads/main/recieve.lua")
print("Installing BasaltGUI API")
shell.run("wget run https://basalt.madefor.cc/install.lua release latest.lua")

-- Installer bugging when getting dependencies in github 